### ISSUE TITLE
Test B2ACCESS with older iRODS

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#101]
Check if current proxy B2ACCESS problems are solved if:
- [ ] we switch the irods docker image back to `4.1.10`
- [ ] we use older unity versions

**Comment by muccix** [comment]
..or testing with the previous Unity version:

b2access-integration.fz-juelich.de (b2access.unity)
- It uses his own ca at [1]
- The CA cert is stored at [2]
- If you have created you oauth client please confirm the email address
and open a ticket in helpdesk. My colleague will accept you client.
- This B2ACCESS instance has its own user database. You have to create
a new user account for yourself.

Best regards,
Sander

[1]: https://b2access-integration.fz-juelich.de:8445/oauth-demo/get_tok
en.jsp
[2]: https://b2access-integration.fz-juelich.de/unitygw/VAADIN/files/b2
access-integration-slcs-ca.pem

**Comment by pdonorio** [comment]
Here's the last working copy of irods 4.1.10:
https://hub.docker.com/r/eudatb2safe/irods/~/dockerfile/

**Comment by pdonorio** [comment]
How to make that image work with current stack.

1) in debug.yml

```yaml
  icat:
    image: eudatb2safe/irods
    command: sleep infinity
```

2) access irods 


```bash
rapydo start
docker exec -it eudat_icat_1 bash

vim /tmp/expect_irods

# WHAT TO CHANGE:
# =======================
# server host name
echo $POSTGRES_HOST >> $SCRIPT
# db port
echo '5432' >> $SCRIPT
# database name
echo "$IRODS_DB" >> $SCRIPT
# database username
echo "$POSTGRES_USER" >> $SCRIPT
# database password
echo "$POSTGRES_PASSWORD" >> $SCRIPT
# =======================

# Close vim and init all
/init

# Check
ils

# Add missing extra new user
iadmin mkuser irods rodsadmin
iadmin moduser irods password icatserver

```

3) Restart and fix

```bash
rapydo start 
rapydo shell backend
restapi init
restapi launch
```

**Comment by pdonorio** [comment]
More fixes inside the icat image:

```bash
cd /opt/certificates/
cp -r caauth simple_ca

cp /etc/grid-security/host* host/
chown -R 990 host/
```

**Comment by pdonorio** [comment]
Ok now I get a token from B2ACCESS using iRODS 4.1.10.

The answer when I use the proxy is still bad:
```bash
2017-09-13 10:12:30,719 [WARNING eudat.apis.common.b2stage:74] Catched exception <class 'struct.error'>
2017-09-13 10:12:30,719 [WARNING eudat.apis.common.b2stage:153] GSS failure:
unpack requires a bytes object of length 4
Exception ignored in: <bound method Connection.__del__ of <irods.connection.Connection object at 0x7f333eeb5e80>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 53, in __del__
    self.disconnect()
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 130, in disconnect
    self.socket.shutdown(socket.SHUT_RDWR)
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by pdonorio** [comment]
The last test to try is to use the icommands just to be sure

**Comment by pdonorio** [comment]
with icommands we see a more understandable error from the server:

```bash
globus_gsi_callback_module: Can't get the local trusted CA certificate: Cannot find trusted CA certificate with hash a6ca2f9b in /etc/grid-security/certificates
```

So we copy the b2access ca files into that path.
Then we come to this error:
```bash

# client side
DEBUG: Client side: GSS-API error initializing context: GSS Major Status: Authentication Failed
DEBUG: Client side: GSS-API error initializing context: GSS Minor Status Error Chain:
globus_gsi_gssapi: SSLv3 handshake problems
globus_gsi_gssapi: Unable to verify remote side's credentials
globus_gsi_gssapi: SSLv3 handshake problems: Couldn't do ssl handshake
OpenSSL Error: s3_both.c:415: in library: SSL routines, function ssl3_get_message: excessive message size

# server side
Sep 13 10:27:02 pid:938 DEBUG: On iRODS-Server side: GSS-API error accepting context: GSS Minor Status Error Chain:
globus_gsi_gssapi: Error during delegation: Delegation protocol violation: read failed
```

**Comment by muccix** [comment]
Results of the tests with the previous iRODS version and the B2ACCESS-integration instance.

- current B2ACCESS Devel and current iRODS version -> not working;
- current B2ACCESS Devel  and previous iRODS version -> not working;
- B2ACCESS Integration and current iRODS version -> works correctly.

It seems that something in the current B2ACCESS Devel instance is no more compatible with iRODS GSI system.
