### ISSUE TITLE
Pushing bigger files

### ISSUE THREAD

**Issue by Vathasav** [EUDAT-B2STAGE/http-api#109]
I have tried to push a file of around 500 mb to irods through http-api. I get the timeout error. Is it due to nginx timeout settings?

I have tried to upload data via streaming, but it is not working as expected. The object is created on the irods side and the server responds success (status 200). However, the object is empty on the irods side. 

Is there any limit on maximum size of the files that can be transferred using API?

**Comment by pdonorio** [comment]
Hi @Vathasav, 
are you testing this on the latest 1.0 or an older instance?

At some point (`rc3` I think) I removed timeout and filesize limits to all nginx instances and uwsgi configuration.

**Comment by Vathasav** [comment]
@pdonorio I am testing it on the latest 1.0 instance.

**Comment by pdonorio** [comment]
Ok; I need more feedback then please:

- what is exactly the output? 
- what are the steps to reproduce the error?

**Comment by Vathasav** [comment]
I am using the api 1.0 in the development mode.

Steps to reproduce the error.

### For streaming
- Input: Tried to stream a 100 Mb of file using the [instructions](https://github.com/EUDAT-B2STAGE/http-api/blob/master/docs/user/registered.md#example-streaming-upload)
- Output: API responds with status 200 and shows the response

On the irods side, the file is created but is empty (size is 0). 

### Form upload
- Input: Try to  upload a 500 Mb of file 
- Output: 
```bash
http: error: ConnectionError: ('Connection aborted.', timeout('The write operation timed out',)) while doing PUT request to URL:
```

**Comment by pdonorio** [comment]
> For streaming
> On the irods side, the file is created but is empty (size is 0)

I was able to reproduce the bug. I remember that @muccix found something similar in the past where `request.data` was consumed before irods could write the content in the socket, I should inspect this problem with him.
This is important and to be fixed urgently

> Form upload

I don't get any timeout here, it works on my local version on a laptop.
The output on irods is 500M as well.

> I am using the api 1.0 in the development mode

I did use also the development mode. Since there is no nginx or production wsgi in place it is very strange this timeout on your side. I'm not even aware of a Flask timeout, so maybe it's on your `curl` client side (if you used curl)?

**Comment by pdonorio** [comment]
- The bug is confirmed on 1.0.1 and rapydo 0.6.0 as well.
- Unittests checked only the response status, content check to be added

Note: I may use this issue as well to test a bash cycle on the current prototype that was reported to fail once in while

**Comment by pdonorio** [comment]
The bug was found by Roberto and fixed. 

The problem shifted now on the unittest level: there I'm still unable to upload with the Flask testing suite a working file in streaming.

**Comment by pdonorio** [comment]
The simplest check for serial different tasks

```bash
#!/bin/bash
for i in `seq 1 1024`;
do
curl -o /mnt/io/io${i}.dd $SERVER/api/registered/sdcCineca/home/guest/${i}.dd?download=true -H Authorization:"Bearer $TOKEN"
done
```

**Comment by pdonorio** [comment]
Branch `1.0.1` has the patch, also with [unittests](https://travis-ci.org/EUDAT-B2STAGE/http-api/builds/312376266).

@Vathasav could you test this branch?
You can re-clone the repo and follow the [quick start](https://github.com/EUDAT-B2STAGE/http-api/blob/1.0.1/docs/quick_start.md#a-debug-instance-in-few-commands).

**Comment by Vathasav** [comment]
This docker instruction is failing when testing 1.0.1: 
```bash
RUN pip3 install --upgrade --no-cache-dir git+https://github.com/rapydo/http-api.git@$RAPYDO_VERSION
```
Could not find a version that satisfies the requirement python-irodsclient==0.7.0a0 (from rapydo-http==0.6.0)

Is it python-irodsclient==0.7.0?

**Comment by pdonorio** [comment]
> Is it python-irodsclient==0.7.0?

Yep, it changed recently: https://github.com/irods/python-irodsclient/releases/tag/v0.7.0

I fixed the constraint which was necessary because 0.6.0 did not work.
To update with the patch you could try:

```bash
rapydo update --rebuild
```

**Comment by Vathasav** [comment]
Tested streaming on 1.0.1 and is working fine. 

You are right about client timeout! I forgot to adjust client timeout while pushing large files.

What do you think of adding a small note in the [instructions](https://github.com/EUDAT-B2STAGE/http-api/blob/master/docs/user/registered.md#example-streaming-upload) about adjusting clients (curl, HTTPie) timeout in case of pushing large files?

**Comment by pdonorio** [comment]
> What do you think of adding a small note

done

**Comment by pdonorio** [comment]
Completed the tests with this script:

```bash
#!/bin/bash

export TOKEN=""
export SERVER='https://YOURSERVER'
export APIHOME='/zone/home/USER'
export inputfile='myfile'

for i in `seq 1 1024`;
do
        echo $i

        ## UPLOAD
        nohup dd if=/dev/zero of=$inputfile bs=1048576 count=10
        echo up $i
        curl -X PUT \
               -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/octet-stream" \
               -T $inputfile $SERVER/api/registered/$APIHOME/file${i}?force=true

        ## DOWNLOAD
        curl -o /tmp/file${i} \
                -H "Authorization: Bearer $TOKEN" \
                $SERVER/api/registered/$APIHOME/file${i}?download=true

done
```

No issues in uploading and downloading from an external host all of this.
