### ISSUE TITLE
Add coverage badge

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#11]
Coverage is working, but it looks like there is more actions requested to have a badge about coverage, instead of only the one about builds.

Let's do this ^_^

**Comment by muccix** [comment]
I have tried to use coveralls (https://coveralls.io/) but it seems that the data related to the coverage are not "seen" by coveralls (as you can see here https://coveralls.io/github/EUDAT-B2STAGE/http-api).  
My suspect is that this is because the coverage is executed inside a docker container.

**Comment by pdonorio** [comment]
Uhm, probably it expects some files/directory in some places.
We can make Docker write them in the right place if we know where.

**Comment by pdonorio** [comment]
This has been resolved, see https://eudat-b2stage.github.io/http-api/
