### ISSUE TITLE
Discussion: Publishing iRODS collections

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2STAGE/http-api#113]
One can also label iRODS collections with "publish" but it is not handled well in the current implementation

Tagging a folder with several files in it as "public":

```sh
curl -H "Authorization: Bearer $TOKEN" $SERVER/api/registered/cinecaDMPZone1/home/cstaiger/upload

"Response": {
    "data": [
    ...
    "dataobject": "file10G"
    ....
    "dataobject": "file2G"
    ....
    "dataobject": "my.png"
    ....
    "errors": null
  }
}
```

```sh
curl -X PUT -H "Authorization: Bearer $TOKEN" $SERVER/api/publish/cinecaDMPZone1/home/cstaiger/upload
```

The HTTP API informs me that listing is not implemented when accessing the folder by browser.
However, the files in the folder are also not accessible. So we are missing some recursive propagation of the "publish" tag.

I wonder whether publishing iRODS collections should be made publicly available. How would you deal in such a case with nested collections?

**Comment by pdonorio** [comment]
No REST API operation should ever be designed to be recursive.

APIs should be atomic giving the freedom to people to create their wrappers/script for any batch processing.
For example at the moment the DELETE method on the registered files is not available for a collection: you can list your files with a GET and do a for cycle to remove one by one. The same should apply to publishing. 

For that reason I think it is just a matter of understanding what to respond to a user trying to publish a collection: not allowed, forbidden, etc.; but the recursion will never be applied, the API could hang on such operation with nested subelements and not respond before timeout.

**Comment by pdonorio** [comment]
Here I should fix the response for a collection

**Comment by pdonorio** [comment]
Fixed
