### ISSUE TITLE
API Endpoints specifications

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#12]
Based on the latest f2f meeting, try to stay as close as possible to the B2SHARE model, but most of all to the latest data/metadata model discussed.
- ~list errors to be tested~
- ~a status endpoint to check all internal sub-services (irods, graph, and so on)~

**Comment by pdonorio** [comment]
B2SHARE documentation here:
https://eudat.eu/services/userdoc/b2share#UserDocumentation-B2SHARE-TheB2SHAREHTTPRESTAPI

**Comment by pdonorio** [comment]
This is starting to look in better shape since we have better standards from EUDAT-B2STAGE/http-api-base#7

**Comment by pdonorio** [comment]
I also have some notes to convert from the f2f in Rome

**Comment by pdonorio** [comment]
I can use this issue to track the conversion into compatibility of the eudat api from the new response.

It is perfectly normal that tests fails now:
https://travis-ci.org/EUDAT-B2STAGE/http-api/builds/126632115

**Comment by pdonorio** [comment]
Update the API server image:

https://hub.docker.com/r/eudatb2safe/apiserver/builds/bifuftqlbmul2zkyhxrfjbh/

**Comment by pdonorio** [comment]
A question about the data modeling:

Is a zone a part of the collection or should it be a separated parameter to be passed to the REST API endpoints?

Could you give us your opinion @cjhak ?

**Comment by cjhak** [comment]
@pdonorio, what zones are you thinking of? Zone as in iRODS zones?

Also, please remember that the data models differ between iRODS, old B2SHARE, new B2SHARE 2.0 and the EUDAT data model which is still work in progress (e.g. "collection" means different things between them). I'm currently working on updating the HTTP API specs doc again, following up on discussions in the Technical Committee meeting day before yesterday, so I will send a new version to you for review soon.

**Comment by pdonorio** [comment]
At the moment we are thinking of Zones as iRODS zones.
This is a problem originated from iRODS itself, because the path received in `ils` is both Zone + Collection.

But we will wait for this new version of the spec to go further inside this issue 👍

**Comment by cjhak** [comment]
@pdonorio what are you using this path for? Is this what I call <ID> for the digital object/entity URIs in the specs and the slides I showed in Rome, that is what identifies it as the particular resource (or "endpoint")?

**Comment by pdonorio** [comment]
In my notes from the hackathon we excluded the path from being used for the URI, because it contains the slashes and it is misleading as <ID>. 

So the path could be used as a possible filter, once we decide what the <ID> is. Probably we could discuss this further tomorrow in our call.

**Comment by pdonorio** [comment]
I just understood with @mdantonio that we should write some utilities that help test any endpoint based on the design principles. Will open an issue for that.

**Comment by pdonorio** [comment]
@cjhak using specs of jsonapi.org + neo4j inside the issue EUDAT-B2STAGE/http-api-base#22, we managed with @mdantonio to test UUID/IDs from REST API.

I will show them at the developer meeting within the demo, I hope it will help the discussion about using the graphdb for metadata store AND following specifications with automatic functions.

Here there is a sample of a /api/dataobject output for now:
```json
HTTP/1.0 200 OK
Content-Length: 1555
Content-Type: application/json
Date: Thu, 16 Jun 2016 09:24:28 GMT
Server: Werkzeug/0.11.10 Python/3.5.1+

{
    "Meta": {
        "data_type": "<class 'dict'>",
        "elements": 2,
        "errors": 0,
        "status": 200
    },
    "Response": {
        "data": {
            "content": [
                {
                    "attributes": {
                        "filename": "test.txt",
                        "location": "irods://rodserver:1247/tempZone/home/guest/test.txt",
                        "path": "/tempZone/home/guest/test.txt"
                    },
                    "id": "d1c068cc-1eda-4390-96ee-109e57e714fe",
                    "links": {
                        "self": "http://api:5000/api/dataobjects/d1c068cc-1eda-4390-96ee-109e57e714fe"
                    },
                    "relationships": {
                        "belonging": [
                            {
                                "attributes": {
                                    "name": "guest",
                                    "path": "/home/guest"
                                },
                                "id": "1f2e30f9-692e-4404-881a-97e4f8240e0e",
                                "type": "collection"
                            }
                        ],
                        "located": [
                            {
                                "attributes": {
                                    "name": "tempZone"
                                },
                                "id": "-",
                                "type": "zone"
                            }
                        ],
                        "stored": [
                            {
                                "attributes": {
                                    "name": "myResc"
                                },
                                "id": "-",
                                "type": "resource"
                            }
                        ]
                    },
                    "type": "dataobject"
                }
            ],
            "links": {
                "last": null,
                "next": null,
                "self": "http://api:5000/api/dataobjects"
            }
        },
        "errors": null
    }
}

```

**Comment by pdonorio** [comment]
This might be completed with #35

**Comment by pdonorio** [comment]
Issue 35 was done
