### ISSUE TITLE
Config CELERYUI_USER and CELERYUI_PASSWORD not used?

### ISSUE THREAD

**Issue by merretbuurman** [EUDAT-B2STAGE/http-api#129]
Could it be that the CELERYUI_USER and password from config are not being used (at least not for loggin into the GUI)? I can not use the values from my config to login to the UI, but I can login using values from workers.yml.

Please see this line:
https://github.com/EUDAT-B2STAGE/http-api/blob/1.0.4/projects/b2stage/confs/workers.yml#L55

Here, the values from config are read, but they do not seem to be used:
https://github.com/EUDAT-B2STAGE/http-api/blob/1.0.4/projects/b2stage/confs/workers.yml#L69

**Comment by mdantonio** [comment]
I confirm that credentials are fixed and hardcoded.

Now i changed it (to test you have to update both main repo and submodules/rapydo-confs)

I'm also working on flower persistency but it is still not fully working, so that in a near future (I hope) i will change again the flower starting command

**Comment by mdantonio** [comment]
@merretbuurman can be closed now?
