### ISSUE TITLE
SeaData delete orders: Missing function name in return JSON for deleting orders.

### ISSUE THREAD

**Issue by merretbuurman** [EUDAT-B2STAGE/http-api#131]
Just a small thing:
Missing function name in the JSON that is being sent to the client API: **api_function': 'unknown_function_ready'**

```
celery_1        | 2018-10-29T18:26:01.982087506Z [2018-10-29 18:26:01,980: INFO/ForkPoolWorker-1] {'parameters': {'request_id': 'not_sure_what_they_want_here_either'}, 'request_id': 'c93f6e1b-39b6-4db1-ad57-0d7a434831c2', 'errors': [{'error': '4016', 'description': 'Order does not exist or you lack permissions', 'subject': '123'}, {'error': '4016', 'description': 'Order does not exist or you lack permissions', 'subject': '234'}], 'edmo_code': '4587', 'datetime': '20181029T18:26:01', 'api_function': 'unknown_function_ready', 'version': '1.0.4.0011'}
```

**Comment by merretbuurman** [comment]
The function name has to be set by the client, so this is not a problem of the http-api, but of my client script! Sorry for this.

**Comment by mdantonio** [comment]
Yes, I confirm that the response simply echoes the input parameter (defaulted to 'unknown_function') by adding the _ready suffix. The reason is that this parameter is not used by HTTP-API/CELERY but only by the requestor
