### ISSUE TITLE
B2HANDLE integration?

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#14]
This issue is to figure out whether we need to interact with B2HANDLE inside the HTTP-API. 

I guess the registration of new PIDs is in charge of B2SAFE: probably the HTTP-API should than be able to return the PID to the user.
If I'm not wrong, B2SAFE already know the PIDs of the files ingested, so we don't need to use B2HANDLE to get those PIDs (this must be verified with Claudio Cacciari).

In my opinion the ability to resolve a PID and to perform a reverse look-up (from URL to PID) is in charge of B2HANDLE itself, so we shouldn't consider the development this kind of APIs.

**Comment by pdonorio** [comment]
> If I'm not wrong, B2SAFE already know the PIDs of the files ingested, so we don't need to use B2HANDLE to get those PIDs (this must be verified with Claudio Cacciari).

We probably have to integrate the iRODS rules for the Docker image of B2SAFE, but I agree that @ccacciari should confirm. I remember that he was testing the .metadata file to keep track of PIDs metadata inside iRODS FS.

> In my opinion the ability to resolve a PID and to perform a reverse look-up (from URL to PID) is in charge of B2HANDLE itself, so we shouldn't consider the development this kind of APIs.

We might have to discuss in Barcelona what and if we want to save about PIDs inside the GraphDB as a local metadata store. If used we could at least provide (some elements of) the list of PIDs for collections without using B2SAFE or B2HANDLE scripts. What do you think?

**Comment by muccix** [comment]
The can be discussed in #45
