### ISSUE TITLE
Critical mixed up config values.

### ISSUE THREAD

**Issue by merretbuurman** [EUDAT-B2STAGE/http-api#140]
During enabling, the data should be written into a directory on the host (e.g. on the NFS share), defined by `RESOURCES_LOCALPATH`.

In the ingestion.py, instead of `RESOURCES_LOCALPATH`, the value of `SEADATA_RESOURCES_MOUNTPOINT` was used. `SEADATA_RESOURCES_MOUNTPOINT` is the location where data is located *inside* the containers ( `/usr/share/...`), not on the host filesystem (where is it usually something like `/nfs/share`).

This error causes the enabling + upload to break, unless there is a link from `nfs/share`to `/usr/share` on FS level, or they coincidentally have the same value.

Proposed fix: Use `RESOURCES_LOCALPATH` during any filesystem reads or writes which are outside containers (and outside irods).

**Comment by mdantonio** [comment]
HTTP api cannot write on a directory on the host.
The host folder LOCALPATH is mounted into the container as MOUNTPOINT

Are you running with --mode production?
In this case, please run with --mode seadata and everything should work

**Comment by merretbuurman** [comment]
Hi,
thanks for the very quick reply! Yes, that makes sense, as b2stage also runs in a container. I was running it with production, will test with seadata and close the issue then.

**Comment by merretbuurman** [comment]
Tested in seadata mode, it works, so this issue is not an issue and needs no solving. Closing it.
