### ISSUE TITLE
A celery task for reading metadata and save it into the graphdb

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#18]
Based on the previous work of B2SAFE:

https://github.com/EUDAT-B2SAFE/B2SAFE-core/tree/metadata/scripts/metadata

**Comment by mdantonio** [comment]
I'm working on a very similar use case: when importing files into a dataset I have to read/parse the file to extract/compute metadata to be stored in graphdb

My POST /files endpoint is implemented with the following operations:
- import the file into irods
- create a neo4j node with file information
- call a Celery task to  extract metadata
- update the file node to save the task.id and the extraction status (SENT->RUNNING->COMPLETED)

The Celery task is still to be implemented (cannot be implemented now due to a bug in custom models loading). Action to be performed:

- access to both graphdb and irods
- update file node (status = RUNNING)
- cp file from irods to local
- read file / parse content / extract metadata / compute metadata
- update file node with metadata
- update file node (status = COMPLETE)

**Comment by pdonorio** [comment]
> My POST /files endpoint is implemented with the following operations

That is exactly our second call which will be used as described in  EUDAT-B2STAGE/http-api#16

> The Celery task is still to be implemented 

How can I help you?

**Comment by mdantonio** [comment]
> How can I help you?

I think that once fixed the "custom model problem" I will be able to implement this task. On Tuesday we can discuss about similarity and differences to re-use my implementation

**Comment by mdantonio** [comment]
I implemented a full working celery task to extract metadata from a file (implemented with a very simple metadata, the number of lines, but can be expanded as needed)

input: (node identifier on neo4j, file path on irods)

- retrieve node from neo4j -> update extraction status 
- create a random name for temporary file
- iget file from irods to local disk (using the random name)
- open file to count the number of lines (here more complex operations can be added)
- delete temporary file
- update node with computed metadata

**Comment by pdonorio** [comment]
We have requirements for EUDAT: 
- a `METS` file to specify where the metadata is described
- at least a manifest in `XML` format which describes where metadata is and how to extract it.

That's were we differ from your current schema specifications, right?

**Comment by mdantonio** [comment]
Of course what changes is the way metadata are extracted. For example i will use several parser, based on the input file extention (i.e. fastq, bam, vcf) and you will perform different actions.

The general schema is probabily the same (copy file from irods to local, read file, [get metadata], write metadata, delete temporary file)

[get metadata] operation should be customized, other operation could be generalized (to be discussed on Tuesday)

**Comment by pdonorio** [comment]
One endpoint that could help here is the admin endpoint to check the current queue and the status of each task

**Comment by pdonorio** [comment]
STEP 1: write b2safe models as described [here](https://github.com/EUDAT-B2SAFE/B2SAFE-core/blob/metadata/scripts/metadata/b2safe_neo4j_client.py#L21). Our actual models are instead based on [this old idea](https://github.com/pdonorio/irods2graph#models)

Differences:
- Digitalentities instead of Dataoboject
- Person instead of IrodsUser pointing to HTTP API User
- Aggregation instead of collections
- Pointers for Replica and Master, instead of pointing to dataobjects
- Metadata does not exist

**Comment by pdonorio** [comment]
STEP 2: copy the [manifest folder](https://github.com/EUDAT-B2SAFE/B2SAFE-core/tree/metadata/scripts/metadata/manifest)  and try to execute [this code](https://github.com/EUDAT-B2SAFE/B2SAFE-core/blob/metadata/scripts/metadata/b2safe_neo4j_client.py#L565-L578)

**Comment by muccix** [comment]
I'm trying to understand and import the model proposed by B2SAFE ([here](https://github.com/EUDAT-B2SAFE/B2SAFE-core/blob/metadata/scripts/metadata/b2safe_neo4j_client.py#L21)). Some inputs from Claudio Cacciari:

- Using "DigitalEntities" intsead of "DigitalObjects": we can infer that a DigitalEntitey is a DigitalObject form its properties (such as PID presence)

- "Aggregation" is used to explicit generic relations between objects (not physical as a collection can represent); an example: ten entities containing data related to the same geographical area

- "Pointers" are used to represent relations (IS_MATER_OF or IS_REPLICA_OF) with entities outside the current iRODS deployment which we don't have all the information of. It's just a tentative implementation that can be changed.

**Comment by pdonorio** [comment]
> User metadata are actually files on iRODS, so they can be considered as DigitalEntities

We may add a metadata node for every submetadata we want to store inside the graphdb. These way we end up with metadata connected to the digitalentity, storing for example some JSON content directly as native neo4j attribute

**Comment by pdonorio** [comment]
@muccix  An example for using neo4j models inside an endpoint is available [here](https://github.com/EUDAT-B2STAGE/http-api/blob/metadata_parser/vanilla/apis/internals/b2safe.py#L24-L47).

In DEBUG mode, use the endpoint with the client_shell:
```bash
http GET apiserver:5000/api/internals/metadataobj Authorization:'Bearer YOUR_TOKEN_HERE'
```

To see what happens on the graph: http://localhost:9090/browser/

**Comment by pdonorio** [comment]
I updated the code [and the client image](https://github.com/EUDAT-B2STAGE/http-api/issues/22#issuecomment-244870000).

Please update the code and the docker images:
```
./do update
```

Note: tests fails now, since we don't have collections and dataobjects available.

**Comment by pdonorio** [comment]
We discussed internally a new roadmap, which we should define with Milestones.

This important issues goes on hold until the end of October.

**Comment by pdonorio** [comment]
No time/effort for the first stable release.
