### ISSUE TITLE
"normal" execution needed

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2STAGE/http-api#19]
Hi,

If we are ever going to run the http-api it needs to be a standard product without docker and supporting python v2.6.

There is no installation document to do so.

How can we do this?

Greetings,

Robert Verkerk

**Comment by pdonorio** [comment]
Hi Robert,

since the api-base is the core of the project, EUDAT-B2STAGE/http-api-base#26 is enough to track these development on the whole project. 

I will close here and monitor the other 2 issues for docker and python 2.
