### ISSUE TITLE
First upload endpoint

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#2]
Implement authenticated uploading of a file into irods resource

**Comment by pdonorio** [comment]
- [ ] extend [uploader class](https://github.com/pdonorio/rest-mock/blob/master/restapi/resources/services/uploader.py#L68)
- [ ] iput of uploaded file
- [ ] remove uploaded file from local filesystem
- [ ] **failure recovery**? caching on the local filesystem if iput does not work

**Comment by pdonorio** [comment]
A first raw upload is completed.

Next step is to copy the uploaded file to irods with iput, and remove the local (cache) file.

**Comment by pdonorio** [comment]
@muccix tested successfully the upload with `httpie` and `requests` 

:facepunch:

**Comment by pdonorio** [comment]
Note to my self: 

Can we try to avoid the **flask save** and put directly the (temporary) file into irods?

Should we do so? This probably would break the possibility to cache.
Also: i don't really know if it would save us time, as i think the flask save it's a just a Unix move (`mv`) command in fact.

Should check

**Comment by pdonorio** [comment]
How to test the upload with `httpie`:

```bash
http --form POST SERVERNAME:SERVERPORT/api/dataobjects file@PATH/TO/FILE/TO/UPLOAD
```

**Comment by pdonorio** [comment]
This endpoint is now almost done.

@muccix what do you think about the last two questions?

in particular:

>  let the user specify the collection?

**Comment by pdonorio** [comment]
Design proposal for the new parameter:

1. The 'path' parameter should be a collection.
2. It must not contain the Zone and cannot contain the name file in the end.

**Comment by pdonorio** [comment]
What about a name option?

**Comment by muccix** [comment]
I would prefer not to add too many option since we don't have clear specifications

**Comment by pdonorio** [comment]
So we can close this one. YEAHI!

**Comment by muccix** [comment]
Is the "collection" parameter expected to work? I have added a test which uses is but it fails..

**Comment by pdonorio** [comment]
It should. Can you link me the test?
There may be a bug or probably we must discuss how it should work.

Also a note: tests for the http-api should be placed inside the `http-api` repo.
We have to use the directory `vanilla` and link something from there inside the tests directory of the backend. That's on me.

**Comment by muccix** [comment]
This is the test: 
https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/test/test_dataobjects.py#L47

I have also tried with httpie:
$ http -f POST 130.186.13.24:8080/api/dataobjects file@test.txt collection='/tempZone/home/guest/'

"errors": [
            {
                "iRODS": "The requested collection does not exist"
            }
        ]

**Comment by pdonorio** [comment]
The point is that `/tempZone` is the Zone. I initially wrote the idea in [my comment](https://github.com/EUDAT-B2STAGE/http-api/issues/2#issuecomment-206228075) above.

So at the moment the zone should be not specified inside the `collection` parameter. 
We could discuss if we should add the `zone` parameter instead, which is much clearer.

**Comment by muccix** [comment]
You are perfectly right! I'm going to correct the test
