### ISSUE TITLE
Update docker images

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#22]
- [x] Irods can be started with no validation, developers wrote me on gitter
- [x] We should be based on Ubuntu LTS 16.04 (instead of 15.10 as currently)
- [x] We could try to use alpine for all services, because it's the OS that Docker directly supports

**Comment by mdantonio** [comment]
I add here a piece of log from Celery, maybe we could consider to add a non-root user for Celery

```
/usr/local/lib/python3.5/dist-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

```

**Comment by pdonorio** [comment]
What username should I add? Something like "developer"? Or "worker"?

**Comment by mdantonio** [comment]
> What username should I add? Something like "developer"? Or "worker"?

Yes, something like that (just to remove the warning)

**Comment by pdonorio** [comment]
Updated the eudat server image, downloaded and tested

**Comment by pdonorio** [comment]
> Yes, something like that (just to remove the warning)

I already found the guest user inside. Is that enough?

```bash
docker run -it --user guest eudatb2safe/apiserver bash
guest@2a186e5f030d:/tmp$
```

**Comment by pdonorio** [comment]
I [updated the apiclient](https://hub.docker.com/r/eudatb2safe/apiclient/builds/b7eakavnslxwkyl8yiyf7hx/) to be based on the alpine `edge`.

It includes now the [jq library](https://stedolan.github.io/jq/) for parsing the JSON response from `http` calls.
I also added a script `/tmp/gettoken` to easily authenticate and have variables to avoid writing the long token string.

This image has become very good so far, it has bash & vim, and probably could be a base for the other images, like the `apiserver`. We need irods thought, so [I asked them on twitter](https://twitter.com/irods/status/772933456552755200). Probably they will support us if we have problem on that build.

**Comment by pdonorio** [comment]
Had a lot of troubles after updating to latest ubuntu and latest irods:

- iCAT 4.1.9 doesn't let you install the GSI plugin...! I had to revert to 4.1.8
- On ubuntu 16.04 some packages content changed
- Also the default certification authority is not there anymore. I had to go through many tests to find how to build one on `./do init`

I found [this](http://irods.org/2015/12/setting-up-irods-with-gridftp-using-b2stage-gridftp/) and [that])(https://github.com/WillemElbers/B2SAFE-GridFTP) useful in the process.

All should be solved now with [this commit](https://github.com/EUDAT-B2STAGE/docker-images/commit/f4d4709866e949ac966b75b9c7e6e5d463dcf283).

**Comment by pdonorio** [comment]
Plugins from irods were update to match the 4.1.9 release.
http://irods.org/2016/09/updated-plugins-for-irods-4-1-9-are-released/

We may test the update to see if there is any performance gain.

**Comment by pdonorio** [comment]
Updated locally to the latest ubuntu 16.04 with iRODS 4.1.9. It's not working, irods calls with certificate give the following error:
```bash
[-]	libgsi.cpp:1208:gsi_auth_client_request :  status [PLUGIN_ERROR_MISSING_SHARED_OBJECT]  errno [] -- message [call to rcAuthPluginRequest failed.]

 failed with error -1827000 PLUGIN_ERROR_MISSING_SHARED_OBJECT
```

I am giving up for the pre-production release on this.
Let's put it to hold.

**Comment by pdonorio** [comment]
A quick note on alpine: it's very difficult to build and use iRODS or GSS with that OS at the moment. We should move our effort for iRODS towards the support of python3 of their libraries.

**Comment by pdonorio** [comment]
Just noted that I have to update icommands/gsi also on the irods client (the flask server side)...

**Comment by pdonorio** [comment]
Still no luck

**Comment by pdonorio** [comment]
After failing to use irods 4.1.9 I did a full clean:
- deleted the images with `docker rmi eudatb2safe/b2safe eudatb2safe/apiserver`
- cleaned the project with `./do clean`
- initialized back with `./do init` which pulls back the latest version of the docker images above

And then launched the server, and irods icommands via flask gave me no errors.
Please @muccix follow the steps above and let me know if you still have problems.

**Comment by pdonorio** [comment]
Note that 4.1.9 has been a buggy version, as there was a quick release of 4.1.10 to solve problems: http://irods.org/2016/11/irods-4-1-10-is-released/

**Comment by pdonorio** [comment]
We may try, just in case, the release 4.1.10 very soon:
http://irods.org/2016/11/updated-plugins-for-irods-4-1-10-are-released

**Comment by pdonorio** [comment]
Uh oh, 4.2 of irods is out 😱 
http://irods.org/2016/11/irods-4-2-0-is-released

**Comment by pdonorio** [comment]
Note: I had quite some problem in the past with this error in GSI:

```bash
Error with GSS token: The input token has an invalid length of: 0
```

Today it came back with no reason. After 2 hours, 2 docker clean, and 1 laptop reboot, but without changing code, it just went away. I have the feeling that it was somehow related to some file permissions or to errors in generating the proxy. Logging this anyway.

**Comment by pdonorio** [comment]
> Error with GSS token: The input token has an invalid length of: 0

I have this error every once in a while. It is related to B2ACCESS having problems in authenticating most of the time.

**Comment by pdonorio** [comment]
Trying now the update to iCAT 4.2.0
This will involve for the first time using local **builds** instead of a dedicated public docker image, see mdantonio/rapydo#18

I will close this issue after that.

**Comment by pdonorio** [comment]
The issue above is completed.

We may re-open in case we want to dig more on building the B2SAFE better on Docker on the 4.2 irods
