### ISSUE TITLE
Concept of data domains

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#23]
The most basic endpoint for Download and Upload.

Since we are dropping the IDs for the pre-production release,
we will have this configuration:

```
/api/digitalentities/<FILENAME: string>

GET / POST / PATCH (modify filename) / DELETE

optional parameters:
- path (zone + nested collections) [default: irods home directory]
- resource (irods Resource) [default: irods default resource]
```

Note: iRODS is the only service required in this endpoint class

**Comment by pdonorio** [comment]
Decide also about the [standard response](https://github.com/EUDAT-B2STAGE/http-api-base/issues/7#issuecomment-245183154)

**Comment by pdonorio** [comment]
I think this issue is outdated now.

The key point for our B2STAGE HTTP API is the *namespaces* domain, instead of the EUDAT main data model.

There will be two main namespaces:
1. The **workspace** domain, a sort of staging area where the researcher upload the file, make quality checks and analysis, validate and filter. This is the normal file system workspace.
2. The **registered** domain, where the researcher can publish the data obtained from the workflows in the previous domain. This is the EUDAT B2SAFE data domain, where data is registered with a PID.

The PID itself is a namespace which should be considered too.

**Comment by muccix** [comment]
Opening a separate issue for this: "The PID itself is a namespace which should be considered too."

**Comment by pdonorio** [comment]
The workspace domain should be discussed in the near future, anyway I like the idea of using something like [pathlib](https://docs.python.org/3/library/pathlib.html) to abstract the layer.

**Comment by pdonorio** [comment]
So the workspace domain isn't something the communities really requested about at the moment. So we could close (for no time/effort for the first stable release) and re-open if really needed.

**Comment by pdonorio** [comment]
More about the python lib for workspace: https://pymotw.com/3/pathlib/
