### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#26]
Update the current docs and README to reflect all the news.
- [x] What are the available endpoints and methods
- [ ] How to login with B2ACCESS
- [ ] Examples of upload/download with curl, http and python code

**Comment by muccix** [comment]
I have started creating some draft user documentation pages e6d32860428f416b8a3df391a2c6f1f6c5c9f31b

**Comment by pdonorio** [comment]
Can we add our latest commits on docs here as reference?

**Comment by muccix** [comment]
User documentation completed 64df7db1fe99190396a3acf8e70d0decac82b26f
