### ISSUE TITLE
Documentation for deployment

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#27]
Instructions needed in our M18 pre-production release:
- [x] How to switch to `iRODS` as external service
- [x] How to deploy with docker
- [x] How to install python (virtualenv?) and requirements 
- [x] Integration from other users

**Comment by pdonorio** [comment]
@muccix can we work on this with Christine? She was also saying at the meeting that virtualenv was not a good choice.

**Comment by muccix** [comment]
To use an ecxternal iRODS:

To make it works:
1. use the correct env variable in the docker-compose.yml and set the B2ACCESS_APPKEY with the B2ACCESS password of the HTTP-API user, for example:

```
# EXTERNAL VERSION
    ICAT_1_ENV_IRODS_HOST: '130.186.13.110'
    ICAT_1_PORT: '1247'
    IRODS_AUTHSCHEME: 'GSI'
    IRODS_USER: 'rmucci'
    IRODS_DEFAULT_ADMIN_USER: 'rmucci'
    IRODS_ZONE: 'cinecaDMPZone1'
    IRODS_CUSTOM_HOME: '/cinecaDMPZone1/home/rmucci'

    ########################
    ## X509 certificates variables
    #CA Authority
    X509_CERT_DIR: /opt/certificates/caauth
    #USER PEMs: Private (key) and Public (Cert)
    X509_USER_CERT: /opt/certificates/rmucci/usercert.pem
    X509_USER_KEY: /opt/certificates/rmucci/userkey.pem
```

2.  Remove the link to the iRODS container in debug.yaml:

```
  #links:
    # IRODS MUST BE CALLED rodserver
    #- icat:rodserver
    # # GRAPHDB MUST BE CALLED gdb
    # - graphdb:gdb
```

**Comment by pdonorio** [comment]
@chStaiger can you create a `0.5.2-docs` branch from `0.5.2`?

**Comment by pdonorio** [comment]
Let me know what and when to discuss for this issue ;)

**Comment by pdonorio** [comment]
> Integration from other users

There's some [testing](https://github.com/EUDAT-B2STAGE/http-api/tree/82c101b57185a54f49cd4db903d60e32023c2672/docs/testing) to check and real feedback on the [quickstart](https://github.com/merretbuurman/http-api/blob/3ad8329d1fd5471f4f2167e4fa1e38e907c69afc/docs/quick_start.md)

Then we may close, hopefully before the webinar

**Comment by pdonorio** [comment]
Moved to the main documentation issue.
