### ISSUE TITLE
Incorrect link to authentication.md on page https://github.com/EUDAT-B2STAGE/http-api/blob/master/docs/user/user.md

### ISSUE THREAD

**Issue by ijjorama** [EUDAT-B2STAGE/http-api#31]
Hi,
The link with text 'Authentication documentation' should have the target
https://github.com/EUDAT-B2STAGE/http-api/blob/master/docs/user/authentication.md

Best Regards,
Ian Johnson.

**Comment by muccix** [comment]
Thanks, fixed
