### ISSUE TITLE
Incorrect link to registered.md on page https://github.com/EUDAT-B2STAGE/http-api/blob/master/docs/user/user.md

### ISSUE THREAD

**Issue by ijjorama** [EUDAT-B2STAGE/http-api#32]
Hi,
The link with text 'namespace api' should have the target
https://github.com/EUDAT-B2STAGE/http-api/blob/master/docs/user/registered.md

Best Regards,
Ian Johnson.

**Comment by muccix** [comment]
Thanks, fixed
