### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#37]
Write a changelog to keep track of releases and of what is about to be released

**Comment by pdonorio** [comment]
@muccix you may take a look here. Close and/or fix the file when you're done.

**Comment by muccix** [comment]
Fine with me: https://github.com/EUDAT-B2STAGE/http-api/blob/master/CHANGELOG.md

**Comment by pdonorio** [comment]
To be updated again

**Comment by pdonorio** [comment]
To be regularly updated with next release.

Note to self: the protocol should be

1. Every issue closed in the milestone, update the changelog, as the issue will partecipate in the next release
2. When merging the pull request, fix the text of the release in the changelog.
3. Release using the same text from markdown
4. Close the milestone
5. Create the new milestone and update the changelog
