### ISSUE TITLE
Investigate alternative to a Python irods client

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#38]
Currently based on a wrap of iCommands, we should look at [the official repo](https://github.com/irods/python-irodsclient/issues/56)

Steps:
- [x] Fork the repo
- [x] Solve GSI (very hard)
- [x] Pull request
- [x] Use 2to3 for testing the repo with Python3
- [x] Support both Python2 and Python3
- [x] Pull request again

Finale step:
- [happiness](http://j.mp/2hgbsaJ)

**Comment by pdonorio** [comment]
Steps to setup the environment:

1. Open the port of the EUDAT http api irods server (1247 in docker-compose)
2. restart the irods server
3. clone the irods repo
```bash
git clone https://github.com/irods/python-irodsclient.git
ln -s python-irodsclient irods
```
4. create a test_gsi.py
```python2
from irods.session import iRODSSession
sess = iRODSSession(
    host='localhost', port=1247, user='rods', password='icatserver', zone='tempZone')
coll = sess.collections.get("/tempZone/home/rods")

print "TEST", sess, coll
```
5. run with python2
```bash
python2 testgsi.py
```

**Comment by pdonorio** [comment]
We have started to integrate the [Python GSS API](https://github.com/pythongssapi/python-gssapi) package in `python-irodsclient`.

Not knowing exactly what to do we [opened an issue](https://github.com/pythongssapi/python-gssapi/issues/110). It seems like we need to handshake a context with certificates credentials. We are still stuck on contacting the iRODS server in the handshake.

So far [this](https://github.com/modauthgssapi/mod_auth_gssapi/blob/master/tests/t_spnego_proxy.py) is the only example of a python context created in another github repo...

**Comment by pdonorio** [comment]
Created [a dedicated image](https://hub.docker.com/r/pdonorio/gsi-python-client/builds/) in the docker hub for testing.

Will update the docker-compose and do in http-api to have a simple command to start it.

**Comment by pdonorio** [comment]
Setting up a way to compile correctly GSI on irods, see [here](https://github.com/EUDAT-B2STAGE/docker-images/tree/master/usecases/irodsgsi) for instructions.

To have it working we must wait [for the new image to be builded](https://hub.docker.com/r/pdonorio/gsi-irods-server/builds/).

**Comment by pdonorio** [comment]
Reached a working security context with [this commit](https://github.com/EUDAT-B2STAGE/python-irodsclient/commit/b5431dc10d907e302659d49b760c3014230b7f2b).

The working client code for the use case with Docker is:
```python
from irods.session import iRODSSession

SERVER_DN = \
    '/O=Grid/OU=GlobusTest/OU=simpleCA-45d266dde38f/CN=host/rodserver'

sess = iRODSSession(
    host='rodserver', port=1247,
    user='rods', password='icatserver',
    server_dn=SERVER_DN,
    zone='tempZone')
coll = sess.collections.get("/tempZone/home/rods")

print "TEST", sess, coll
```

**Comment by pdonorio** [comment]
Things work. Ready for a pull request, waiting for feedback inside the issue.

**Comment by muccix** [comment]
Added support for python3 in the iRODS-python client (see https://github.com/irods/python-irodsclient/pull/62).

We are now ready to replace icommands inside the HTTP-API!

**Comment by pdonorio** [comment]
I'd say we close here. 
A new issue will map the porting of our current class.

**Comment by pdonorio** [comment]
Opened #46
