### ISSUE TITLE
B2ACCESS flow w/o browser

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#39]
- [ ] how to refresh automatically the oauth2 b2access token
~~authenticate to b2access website via command line~~

**Comment by pdonorio** [comment]
> how to refresh automatically the oauth2 b2access token

This is something not possible at the moment, we'll see if B2ACCESS will support it in the future

**Comment by pdonorio** [comment]
> authenticate to b2access website via command line

we have been pointed to this probe:
https://github.com/EUDAT-B2ACCESS/b2access-probe/blob/master/check_b2access.py

**Comment by muccix** [comment]
After discussing this with Willem, it is confirmed that Unity still does not support Token refresh.
Therefore the available option are 2:

1. "Client Credentials Grant Flow" (API need to store users B2ACCESS credentials): see [this](https://github.com/EUDAT-B2ACCESS/b2access-probe/blob/master/check_b2access.py) example
2. "Dynamic token validity enhancement" (see http://unity-idm.eu/documentation/unity-1.9.2/manual.html):

> To enable this feature set accessToken validity to a proper short time (e.g. 30 minutes) - equal to the intended inactive login session time. Additionally set extendAccessTokenValidityUpTo to the intended longest session time (e.g. 12 hours). Then the actively used access token can be valid for up to 12 hours, but will automatically expire after 30 minutes without use.

**Comment by muccix** [comment]
For the time being the "Dynamic token validity enhancement" seems to be a better approach, avoiding the HTTP-API to store user password.

It should work setting the proxy life shorter than the token life, as depicted in the following example:

![dynamic token validity enhancement](https://cloud.githubusercontent.com/assets/7976414/22587483/22fe69f0-ea02-11e6-9cc0-a9aea9648fcb.jpg)

HTTP-API automatically asks for a new proxy when it expires: this interaction triggers the extension of the access token (up to the extendAccessTokenValidityUpTo duration).

On the other hand, If the HTTP-API stops receiving requests from a client, the access token expires within its life time (3h in the example)

I'm going to test this approach.

**Comment by pdonorio** [comment]
> unittest with mocking

we may need some tutorial [like this](https://semaphoreci.com/community/tutorials/getting-started-with-mocking-in-python) for this task

**Comment by muccix** [comment]
At the moment, B2ACCESS Devel has the following settings:

- X.509 proxy: 2 h

- access token: 4 h

- extendAccessTokenValidityUpTo: 24 h

**Comment by pdonorio** [comment]
> how to refresh automatically the oauth2 b2access token

will do now

**Comment by pdonorio** [comment]
I managed to make the renewal work again.

To make it automatic for all endpoints some refactor needs to be done for all b2access utilities, to be moved in the new common package dir.

**Comment by pdonorio** [comment]
Notes:

1. To check the validity of a proxy certificate generated from B2ACCESS:
```
./do server_shell
$ openssl x509 -enddate -noout -in /opt/certificates/USER/*.crt
```

2. There seems to be some cache problem for the irods sessions based on certificates within flask. Even if the certificates is expired it keeps on working. To force it reload the server...

Waiting for production testing to close this issue

**Comment by pdonorio** [comment]
Found some issues, they seem related to PRC

**Comment by pdonorio** [comment]
The issue was NOT cause by `prc` but by [this commit](https://github.com/EUDAT-B2STAGE/http-api/commit/d8f9c82833694a90ef936959bf1d083cff40cebd) :)

**Comment by pdonorio** [comment]
Things here were fixed.
Waiting for tests in production to merge and release @muccix
