### ISSUE TITLE
http api and iRODS mounted collections?

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2STAGE/http-api#41]
Hi,

To my understanding the http api will be able to put and get files to iRODS.
But what if the iRODS instance is setup in a way so it should NOT be able to put data, but only get. This happens if you have a mounted collection in iRODS. Than the data is already on disk. You just need to tell iRODS where it is (with ireg) so the iRODS database is updated. This way the user only needs to have the data in one place and does not need to have duplicate disk space when adding a file in iRODS.

So will the http api be able to deal with this?

**Comment by pdonorio** [comment]
Since there is no time/effort for the first stable release to consider special cases.
We will state this in the documentation.
