### ISSUE TITLE
pids endpoint

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#45]
Created a branch for the new "pids" endpont: 00af790

**Comment by muccix** [comment]
A first hint:

- `GET /pids/<PID>` returns metadata of the resolved file or a list of object if the PID points to a collection
- `GET /pids/<PID>?download` downloads the resolved file

- `PUT /namespace/<iRODS_path>?pid` upload a file and returns the PID (synchronous)
- `GET /namespace/<iRODS_path>` returns metadata with PID (or "not available yet" if not already there)

**Comment by muccix** [comment]
We should discuss (with Claudio Cacciari and Mark?) when to move from "namespace" to "registered"

**Comment by pdonorio** [comment]
> A first hint

That's fine with me

**Comment by muccix** [comment]
First draft implementation of `GET /pids/<PID>`. See 7c00bb8

@pdonorio we need to add the B2HANDLE library inside the rest container

**Comment by muccix** [comment]
The credentials for the Handle test prefix are in the dmp2 machine (130.186.13.115) in the `/opt/eudat/b2safe/conf` folder. We will need them to perform reverse lookup resolution (getting PID passing physical path).

**Comment by pdonorio** [comment]
> we need to add the B2HANDLE library inside the rest container

Ok, will do

**Comment by pdonorio** [comment]
Done, would you check?

**Comment by muccix** [comment]
Tested reverse lookup with B2HANDLE python library (from URL to PID).

Here is the procedure:
1. Get credentials (in my case copied from dmp2 in /opt/eudat/b2safe/conf )
2. Edit the "credentials" file with the pointer to the certificates
3. Import the library:
```
from b2handle.searcher import Searcher
from b2handle.handleclient import EUDATHandleClient
from b2handle.handleexceptions import ReverseLookupException
```
4. Instantiate b2handle with credentials:
```
cred = PIDClientCredentials.load_from_JSON('/home/rmucci00/Devel/EUDAT/b2handle_cred/credentials')
client = EUDATHandleClient.instantiate_with_credentials(cred)
```
5. Create a new handle:
```
PID = client.generate_and_register_handle('842', 'http://b2stage.cineca.it/test')
```
6. Performe the reverse lookup:
```
list = client.search_handle(URL='http://b2stage.cineca.it/test')
>>> print list
[u'842/94a34a08-9825-4a29-8eba-0df8df998aa1']
```
It's time to implement this in the http-api!

**Comment by muccix** [comment]
Actually, It probably doesn't make sense to implement the reverse look up now. We can get the PID of an uploaded object getting the information from the iRODS metadata.
The icommands to be used should be:

`imeta ls -d <irods_data_object_name> PID`

**Comment by muccix** [comment]
For the case:

`PUT /namespace/<iRODS_path>?pid upload a file and returns the PID (synchronous)`

shall we consider a parameter to set a timeout?

**Comment by muccix** [comment]
Strange behavior: I edited the get.yaml and spec.yaml removing the "all" mapping.
The server starts correctly but when I try to run `$ . /code/queryapi list` from the client_shell I get an error and see the following logs on server side:

```
2017-05-15 15:13:54,972 VERY_VERBOSE @flask_ext Injecting model 'Role'
2017-05-15 15:13:54,972 VERY_VERBOSE @flask_ext Injecting model 'User'
2017-05-15 15:13:54,972 VERY_VERBOSE @flask_ext Injecting model 'Token'
2017-05-15 15:13:54,972 VERY_VERBOSE @flask_ext Injecting model 'ExternalAccounts'
2017-05-15 15:13:54,973 DEBUG @flask_ext.flask_auth TOTP is not available
2017-05-15 15:13:54,973 VERBOSE  @rapydo.rest.definition Parameters {'username': 'user@nomail.org', 'password': 'test'}
2017-05-15 15:13:55,007 ERROR @rapydo.decorators (psycopg2.ProgrammingError) relation "user" does not exist
LINE 2: FROM "user" 
             ^
 [SQL: 'SELECT "user".id AS user_id, "user".uuid AS user_uuid, "user".name AS user_name, "user".surname AS user_surname, "user".email AS user_email, "user".authmethod AS user_authmethod, "user".password AS user_password, "user".first_login AS user_first_login, "user".last_login AS user_last_login, "user".last_password_change AS user_last_password_change \nFROM "user" \nWHERE "user".email = %(email_1)s \n LIMIT %(param_1)s'] [parameters: {'email_1': 'user@nomail.org', 'param_1': 1}]
2017-05-15 15:13:55,008 ERROR @rapydo.rest.definition ['(psycopg2.ProgrammingError) relation "user" does not exist\nLINE 2: FROM "user" \n             ^\n [SQL: \'SELECT "user".id AS user_id, "user".uuid AS user_uuid, "user".name AS user_name, "user".surname AS user_surname, "user".email AS user_email, "user".authmethod AS user_authmethod, "user".password AS user_password, "user".first_login AS user_first_login, "user".last_login AS user_last_login, "user".last_password_change AS user_last_password_change \\nFROM "user" \\nWHERE "user".email = %(email_1)s \\n LIMIT %(param_1)s\'] [parameters: {\'email_1\': \'user@nomail.org\', \'param_1\': 1}]']
2017-05-15 15:13:55,008 VERY_VERBOSE @rapydo.rest.response Response method: default_response
2017-05-15 15:13:55,009 INFO     @rapydo.server POST http://apiserver.dockerized.io:5000/auth/login {'username': 'user@nomail.org', 'password': '****'} <InternalResponse 803 bytes [400 BAD REQUEST]>
```
@mdantonio any idea about `@flask_ext.flask_auth TOTP is not available`' ?

**Comment by pdonorio** [comment]
It looks like the sql db init did not go well. I must discuss with @mdantonio about the init phase to make a decision, this also occurred to me. As a workaround for now I can grab that exception and write in a more clearer way "you need to initialize your db again"

About the TOTP, also that is open to discussion.

**Comment by mdantonio** [comment]
> 2017-05-15 15:13:54,973 DEBUG @flask_ext.flask_auth TOTP is not available

TOTP is not available because the python libraries pyotp and pyqrcode are not installed on the backend build. This is not a problem (the message level is only "DEBUG") because the TOTP authentication is not enabled in your configuration.

**Comment by pdonorio** [comment]
>  This is not a problem

Discussing a patch to avoid this. I prefer the developer to clearly state that he wants the TOTP instead of dynamic import

**Comment by pdonorio** [comment]
Note to self: we should try connection to the auth db before any other service.

This would init that db which is the only thing not to be missed.

**Comment by pdonorio** [comment]
This has been solved with recent commits. 

The real problem was irods not connecting because I needed a patch for PRC which I forgot to push.

I should write somewhere that with the b2access unittest we should add one for proxy refresh...

**Comment by muccix** [comment]
Just found out that for the PIDs registered by B2SAFE production the credentials are not required for the resolution. So we can avoid copying the credentials files during deployment

**Comment by chStaiger** [comment]
Yippie!!

**Comment by pdonorio** [comment]
To do:

- remove information about credentials from production instructions
- add them as an option for development instructions (when you use the testing prefix)

**Comment by pdonorio** [comment]
Completed in the quick start file
