### ISSUE TITLE
Test endpoints

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#5]
Implement the first endpoint unit test using nose.

Must be investigated how to setup and tear down the flask server.

The page http://flask.pocoo.org/docs/0.10/testing/ should help..

**Comment by pdonorio** [comment]
This must first start on the `http-api-base` project.

See EUDAT-B2STAGE/http-api-base#5

**Comment by pdonorio** [comment]
Ok, we may discuss more of the tests here now.

**Comment by muccix** [comment]
The basic [tests](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/test/test_dataobjects.py) for the "dataobjects endpoint" are implemented. Now let's improve it by checking:

- [ ] status codes of the response (see https://github.com/EUDAT-B2STAGE/http-api-base/issues/4)
- [ ] error uploading an already existing objects
- [ ] error uploading an object if the collection doesn't exist
- [ ] error downloading non existing object
- [ ] error downloading an object if the collection doesn't exist
- [ ] error if passing parameters in a wrong format

**Comment by muccix** [comment]
The tests will fail until we fix the error response

**Comment by pdonorio** [comment]
It should be ready to be used now

**Comment by pdonorio** [comment]
Added https://github.com/EUDAT-B2STAGE/http-api/blob/master/vanilla/tests/clean_test_data.sh to clean data when tests fails.

Another option would be to give a random name when uploading a file for a test and let fixed only the extension ('pdf', 'jpg', etc.).

**Comment by muccix** [comment]
Started the refactoring of the first endpoint test (partial: only POST and PUT for the moment) 0903098

**Comment by muccix** [comment]
Until we don't have a smart way to clean test files, we have to use icommands.
To act as guest user:
$ export clientUserName=guest

**Comment by pdonorio** [comment]
I created [a bash tool](https://github.com/EUDAT-B2STAGE/http-api/blob/master/vanilla/client/query_api.sh) to help in calling APIs without rewriting all the options (like auth, token and so on). You will find it inside the apiclient, and you may use it with:

```bash
$ ./do client_shell

[...]

bash-4.3$ . query_api.sh help
Usage: . query_api.sh [METHOD]

available methods: get, post, put, delete, clean
```

There is also now [a clean option inside the delete method](https://github.com/EUDAT-B2STAGE/http-api/blob/master/vanilla/apis/basic.py#L362-L380) to be called to remove all the content inside current user, it works only in debug mode, we can enable it also in test mode.

**Comment by pdonorio** [comment]
Check PATCH method and GET response after implementation in #29

**Comment by pdonorio** [comment]
Since 29 is closed we can try to complete the PATCH method.

The GET details can be skipped for now, since there is not a common standard we achieved.

**Comment by pdonorio** [comment]
Completed up to d76ad6cc4b3efee595d71800ab78af8de55a853a

**Comment by muccix** [comment]
We need to find a way to pass both json and non json data in a request

**Comment by pdonorio** [comment]
> We need to find a way to pass both json and non json data in a request

Since this is related to the core, I opened the discussion [here](https://github.com/EUDAT-B2STAGE/http-api-base/issues/20#issuecomment-264408095)

**Comment by pdonorio** [comment]
Closed with a bug fix, following this discovery:

https://github.com/EUDAT-B2STAGE/http-api-base/issues/20#issuecomment-264784634

See https://travis-ci.org/EUDAT-B2STAGE/http-api/builds/181278302
