### ISSUE TITLE
To Check for the beta release

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#51]
List of things to be checked:

- [x] GET with download=true
- [x] irods fix for user dn and password

**Comment by muccix** [comment]
To be fixed in the prototype:

- [ ]  "link": "http://myserver.mydomain.dev/tempZone/home/guest/test" in metadata does not contain enpoint in URL (api/registered is missing)

**Comment by pdonorio** [comment]
> GET api/registered with ?download=false downloads the object

I should check how you do so in `extended.py`

**Comment by pdonorio** [comment]
> POST api/registered with force:true: recursive fodler creation does not seem to work

We may look for a prc wrapper for the recursion, which does not exist in the driver in itself
