### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#59]
A list of bugs, probably for the next milestone

**Comment by pdonorio** [comment]
1) if production (b2safe devel + b2access devel) then askauth -> nginx bad address?

**Comment by pdonorio** [comment]
2. verify swagger ui 3

**Comment by muccix** [comment]
Let me aggregate the list:

- [ ] if production (b2safe devel + b2access devel) then askauth -> nginx bad address?

- [ ] verify swagger ui 3

- [ ] Listing a collection, the returned metadata is missing PIDs. Although, getting metadata for individual files shows PID

- [ ] Creating a file with a deleted filename, the newly created file missing checksum and pid.

**Comment by pdonorio** [comment]
We should take a look into this again next week @muccix

**Comment by pdonorio** [comment]
> restarting iRODS requires a new access token (need to call askauth)

I could not replicate this issue.

While testing this behaviour I noticed that with an irods server down we get an
`http: error: Request timed out (30s).`.

Probably the irods session is based on the python socket timeout. If that one could be smaller than this 30 seconds we would probably be able to tell the user that irods/b2safe is down.

**Comment by pdonorio** [comment]
> verify swagger ui 3

We may ask @chStaiger to help with this. If her answer is yes we can create a separate issue to track it.

**Comment by chStaiger** [comment]
Can you tell me what the issue is and what to test?

**Comment by pdonorio** [comment]
I created #81 to discuss it

**Comment by pdonorio** [comment]
> Probably the irods session is based on the python socket timeout.

Implemented [here](https://github.com/rapydo/http-api/blob/0.5.3/restapi/flask_ext/flask_irods/__init__.py#L153-L170)
