### ISSUE TITLE
Chunked upload

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#6]
We could allow upload in chunks to let the user recover from an interrupted upload.

A difficult task which would require some extra expertise.

**Comment by pdonorio** [comment]
See #9 to discuss the implementation

**Comment by akrause2014** [comment]
For reference.
This is the documentation for S3 multipart upload:
http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html
and the equivalent in swift:
http://docs.openstack.org/developer/swift/overview_large_objects.html
In a way the chunked upload again follows a similar pattern to the creation of nested digital objects (a directory containing many parts) but the naming is enforced and there is an ordered sequence of files that can be concatenated, and each segment might not have a valid format/contents on its own.

**Comment by muccix** [comment]
[Here](https://blog.pelicandd.com/article/80/streaming-input-and-output-in-flask) is an example of Streaming input and output in Flask.

@mdantonio has already implemented something similar:

```
from flask import stream_with_context, Response

f = open(path, "rb")
return Response(
    stream_with_context(read_in_chunks(f)),
    mimetype=yourMimeType)


    def read_in_chunks(file_object, chunk_size=1024):
        """
        Lazy function (generator) to read a file piece by piece.
        Default chunk size: 1k.
        """
        while True:
            data = file_object.read(chunk_size)
            if not data:
                break
            yield data
```

**Comment by pdonorio** [comment]
Not time/effort for the first stable release. To be reopened if someone may do it.
