### ISSUE TITLE
PUT operation returning the PID (synchronous)

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#61]
Add a parameter to the PUT methods to receive the PID of the uploaded object in the response message.
The operation is synchronous: the response arrives as the PID is available in B2SAFE (we probably need a timeout here)

**Comment by pdonorio** [comment]
We may use `send_warnings` if PID reaches timeout. 
In that case you send the correct data with the PID `None` and also add "errors" to tell the user that something went wrong with B2HANDLE.

**Comment by muccix** [comment]
Here we go 4c04587.

for the time being, we retrieve the PID from B2SAFE metadata: B2SAFE register the object and stores the PID in the iRODS metadata.

Another option would be to use B2HANDLE to perform a reverse lookup operation (from URL to PID) as tested [here](https://github.com/EUDAT-B2STAGE/http-api/issues/45#issuecomment-290409287).

In my opinion, the current method is easier and does the job

**Comment by pdonorio** [comment]
Uhm, is this one good to be closed then? 
❓
