### ISSUE TITLE
iRODS rules B2SAFE compliant

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#63]
To be able to test the "pids" endpoint and the "GET registered", we need the b2safe docker container to trigger rules for object registration (and deregistration on delete).

We need to add these rules in "etc/irods/core.re":

```
acPostProcForPut
{
  ON($objPath like "/tmpZone/home/guset/*")
  {
    EUDATCreatePID("None", $objPath, "None", "None", "false", *PID);
    writeLine("serverLog","PID Created: *PID for object $objPath");
  }
}
```

and
```
acPostProcForObjRename(*sourceObject,*destObject)
{
  ON(*sourceObject like "/tmpZone/home/guset/*")
  {
    EUDATePIDremove(*sourceObject, "true");
    writeLine("serverLog","PID removed for object: *sourceObject");
  }
}
```

**Comment by pdonorio** [comment]
A little more info to decide if this is important for the first release or is more related to the `B2SAFE dockerized development?

**Comment by pdonorio** [comment]
To be investigated soon, hopefully with the help of @chStaiger

**Comment by chStaiger** [comment]
The python API does not seem to trigger any actions or peps in the irods core.re.
I will investigate this a bit, hopefully until Friday.

**Comment by pdonorio** [comment]
This was implemented during the seadata project, see [here](https://github.com/EUDAT-B2STAGE/http-api/blob/1.0.2/projects/b2stage/backend/apis/commons/b2handle.py#L143-L161)
