### ISSUE TITLE
Anonymous access to iRODS

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#72]
Enable Anonymous access to iRODS.

With Anonymous user, no password is required.

**Comment by pdonorio** [comment]
This issue is very important

**Comment by pdonorio** [comment]
Information about how to create and use an anonymous user inside irods:

https://technical.bestgrid.org/index.php/Installing_an_iRODS_slave_server#Public_and_Anonymous_access

**Comment by pdonorio** [comment]
Notes:

- anonymous can access with no password
- anonymous can do commands like 'iuserinfo'
- reading will not work if anonymous has `read rights` to the file alone. you have to enable permissions also on the folder

**Comment by pdonorio** [comment]
Once you do:
```bash
rapydo shell icat
berods
iadmin mkuser anonymous rodsuser  # reserved name
```

You have access with anonymous by using any password:
```bash
http POST localhost:8080/auth/b2safeproxy username=anonymous password=anything                         

HTTP/1.0 200 OK
```
If empty the HTTP API complain about the missing parameter.

**Comment by pdonorio** [comment]
```bash
imkdir /tempZone/home/anonymous
```

otherwise you get "B2SAFE: Not found (or no permission): /tempZone/home/anonymous" even when you are trying another path

How to enable the public dir for the anonymous user:
```bash
ichmod read public /tempZone/home
ichmod read anonymous /tempZone/home

ichmod read public /tempZone/home/public
ichmod read anonymous /tempZone/home/public
```

**Comment by pdonorio** [comment]
So the anonymous user works.
Things to decide:

- should this user be enabled by default? anyway it should be included in the initial setup (of the `icat` docker image) with an option for the developer to decide if yes or not
- the user is not going to specify a password? in that case we need to modify the authentication accordingly
- how should a user provide access to anonymous/public of his data? moving into the public directory or in some other way?

**Comment by pdonorio** [comment]
- [ ] automatic install anonymous (or give a variable to avoid it)
- [ ] verify b2safe: is anonymous installed (simply list users)
- [ ] endpoint to publish (and de-publish) some data object. Should this work for a collection recursively?

**Comment by pdonorio** [comment]
Yet to do:
- [ ] recursive apply permissions
- [ ] complete unittests

> if activated, allow and endpoint to publish (and de-publish) some data object.

This will not work for a collection recursively in the first draft.
Should it be in the future?

We should then update the docs:
- `get`: to check if published
- `put`: to give read permission to anonymous, meaning **published**
- `delete`: remove read permission to anonymous, meaning **unpublished**

**Comment by pdonorio** [comment]
Yet to do:
- [ ] recursive apply permissions
- [ ] complete unittests

> if activated, allow and endpoint to publish (and de-publish) some data object.

This will not work for a collection recursively in the first draft.
Should it be in the future?

We should then update the docs:
- `get`: to check if published
- `put`: to give read permission to anonymous, meaning **published**
- `delete`: remove read permission to anonymous, meaning **unpublished**

**Comment by pdonorio** [comment]
Completed
