### ISSUE TITLE
Quick start documentation in 0.5.2

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2STAGE/http-api#78]
PID resolution:

You wrote that one needs to provide a credentials file to resolve PIDs. That is not necessary:
You can simply use
	from b2handle.handleclient import EUDATHandleClient
	client = EUDATHandleClient.instantiate_for_read_access()
	client.retrieve_handle_record(handle)

A credentials file is only needed for the creation of PIDs.

**Comment by muccix** [comment]
As far as I know, if the prefix is not public, the credentials are needed also for the resolution.

**Comment by chStaiger** [comment]
Every entry in the global handle registry hdl.handle.net is publicly available. There are some test prefixes that only work on a local handle instance. So a user would indeed need access to the local instance. But in production and for accessing B2SAFE PIDs it is not necessary.

![screen shot 2017-07-20 at 08 58 59](https://user-images.githubusercontent.com/8696302/28404505-e7a03414-6d29-11e7-8654-dcdabfe10d94.png)

**Comment by muccix** [comment]
Thanks, I will check also with Claudio Cacciari (who told that credentials are needed..)

**Comment by chStaiger** [comment]
Will the HTTP API also provide the functionality to create PIDs? If that is the case, one needs a credentials file to authenticate with the local handle server. But then I would make a distinction between data users (only resolving PIDs) and data admins who are uploading data and creating PIDs.

The cleanest solution would be to leave the PID creation to B2SAFE itself (by an event hook, e.g. upload to a certain collection).

**Comment by muccix** [comment]
The PID creation is in charge of B2SAFE: it is triggered by a B2SAFE rule (depending on  uploading location)

**Comment by pdonorio** [comment]
Probably the answer for this was this comment:

https://github.com/EUDAT-B2STAGE/http-api/issues/45#issuecomment-316703962

So we can close now
