### ISSUE TITLE
Switch login endpoint based on B2ACCESS credentials

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2STAGE/http-api#79]
http-api/docs/user/authentication.md

The endpoint /auth/askauth does not work as expected

```sh
mlt0054:~ christines$ curl -X POST http://<fqdn>:8080/auth/askauth -d '{"username":"user@nomail.org","password":"test"}' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   313  100   265  100    48  45384   8220 --:--:-- --:--:-- --:--:-- 53000
{
    "Meta": {
        "data_type": "<class 'NoneType'>",
        "elements": 0,
        "errors": 1,
        "status": 405
    },
    "Response": {
        "data": null,
        "errors": [
            {
                "message": "The method is not allowed for the requested URL."
            }
        ]
    }
}
```

While it perfectly works with

```sh
curl -X POST http://<fqdn>:8080/auth/login -d '{"username":"user@nomail.org","password":"test"}'
{
  "Meta": {
    "data_type": "<class 'dict'>",
    "elements": 1,
    "errors": 0,
    "status": 200
  },
  "Response": {
    "data": {
      "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNzFkMWQ1YzgtMmM1ZC00YzM2LWE3NzktYmYwNWY0ZTYyOThhIiwianRpIjoiZjAzN2E0MzMtYWM0NS00YWI2LThmZDUtMDE5MzkwYTdmYzJlIn0.awP5N9IDg3KW5qgV6-AOsQsj-3PLoZApPT_YlZBXK8I"
    },
    "errors": null
  }
}
```

The swagger interface also suggests that '/auth/askauth' should not be used.

**Comment by chStaiger** [comment]
Ahhh I see, this just works when your HTTP API is connected to B2ACCESS.
That would be worth to mention in the doc.

**Comment by pdonorio** [comment]
"Hello, my dear"!

> The endpoint /auth/askauth does not work as expected

The `/auth/askauth` endpoint is intended to be opened only with the browser, for redirection on the b2access portal. That one works only if you put some credentials for HTTP API in your [B2ACCESS configuration](https://github.com/EUDAT-B2STAGE/http-api/blob/master/projects/eudat/project_configuration.yaml#L21-L25). So two point about this:

- [ ] the documentation should said that clear and loud
- [ ] the endpoint should not be provided if credentials are not configured

> While it perfectly works with

The `/auth/login` endpoint is intended for direct access to authentication inside the postgres db. So two points here too:

- [ ] this endpoint should not be provided in the swagger specs if b2access is activated
- [ ] this could be used as a proxy for authentication with b2safe/irods credentials if b2access is not configured

**Comment by chStaiger** [comment]
Just for clarification.
I used the standard instructions to create a develop HTTP API.
When I use the askauth endpoint in the browser I receive:

```
http://<fqdn>:8080/auth/askauth

ERROR
OAuth Authorization Server got an invalid request.

If you are a user then you can be sure that the web application you was using previously is either misconfigured or buggy.

If you are an administrator or developer the details of the error follows:

The 'httpapi' requested to use a not registered response redirection URI: http://<fqdn>:8080/auth/authorize
```

**Comment by pdonorio** [comment]
That error is from B2ACCESS: it means that your credentials to access b2access as an external app are wrong.

**Comment by pdonorio** [comment]
So to clarify to my self:

- If the server is started in production and B2ACCESS credentials are available, then
  +  `/auth/askauth` is enabled
  +  `/auth/login` is disabled
- On the contrary if in production we connect to an external B2SAFE but no credentials are provided for B2ACCESS, then
  +  `/auth/b2safeproxy` is enabled (the name could change)
  + `/auth/login` is disabled

This also means that for EUDAT in production `/auth/login` is always disabled

**Comment by pdonorio** [comment]
Note: we may also reply with instructions instead of removing the endpoint.

But at least they must be skipped from swagger.

**Comment by pdonorio** [comment]
```python
if production: 
 - disable /auth/login

  if irods.external:
     - enable /auth/b2safeproxy
  if isset(b2access):
     - enable /auth/askauth
```

**Comment by pdonorio** [comment]
> if production: disable /auth/login

Completed

**Comment by pdonorio** [comment]
> if isset(b2access): enable /auth/askauth

Completed

**Comment by pdonorio** [comment]
> if not b2access: enable /auth/b2safeproxy

Avoided to check about irods external, since `b2safeproxy` could also be needed if irods is dockerized.
