### ISSUE TITLE
Remove the http-api-base repository as a submodule

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#8]
We will add it as a normal separated repository, otherwise development is too difficult,
as noted in EUDAT-B2STAGE/http-api-base#5

Things to do:

- [x] Remove the submodule in a clean way. (More instructions [here](https://github.com/EUDAT-B2STAGE/http-api-base/issues/5#issuecomment-213341847))
- [x] Add the pull and push of the normal repo inside the bash script `scripts/run.sh`.

**Comment by pdonorio** [comment]
The submodule has been removed in the most clean way i could.

Now the `run.sh` use the other repo as a simple git repo.

@muccix : this should be tested on travis as soon as possible 😉

**Comment by pdonorio** [comment]
The error we have now is that the configuration for travis is trying to change permissions before the init:

https://travis-ci.org/EUDAT-B2STAGE/http-api/builds/127464934

**Comment by pdonorio** [comment]
@muccix can you confirm that without the submodule your project still works?

So that we can close this issue

**Comment by muccix** [comment]
Yes, it works!

On 04/05/2016 12:44, Paolo D. wrote:
> @muccix <https://github.com/muccix> can you confirm that without the
> submodule your project still works?
>
> So that we can close this issue
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/EUDAT-B2STAGE/http-api/issues/8#issuecomment-216825923>
>

-- 
Roberto Mucci
SuperComputing Applications and Innovation Department
CINECA - via Magnanelli, 6/3, 40033 Casalecchio di Reno (Bologna) - ITALY
Tel: +39 051 6171411 Fax: +39 051
