### ISSUE TITLE
Swagger Interface - /api/admin

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2STAGE/http-api#80]
Sends wrong curl request and one cannot edit the curl request.

The request should be:

```
curl -X GET --header "Authorization: Bearer $TOKEN" 'http://<fqdn>:8080/api/admin'
```

**Comment by pdonorio** [comment]
This endpoint is for testing if your account has administration privileges, it's just a debug helper.

I would leave this out of the production mode. What do you think?

**Comment by chStaiger** [comment]
That was actually another question. If I get the answer "I am admin", does that mean the user is admin in the HTTP API or admin in iRODS?

In production I would leave it out. Maybe provide in the metadata endpoint a function to ask for hte user's role in iRODS.

**Comment by pdonorio** [comment]
> If I get the answer "I am admin", does that mean the user is admin in the HTTP API or admin in iRODS?

In the HTTP API. At the moment HTTP API and iRODS do not have a common user accounting, since the HTTP API talks to B2ACCESS for that.

> In production I would leave it out. Maybe provide in the metadata endpoint a function to ask for hte user's role in iRODS.

Probably you want that in `/auth/profile` endpoint instead

**Comment by pdonorio** [comment]
Removing the user helpers from production in rapydo `0.5.4`. 

Created #91 for the other point.
