### ISSUE TITLE
Upgrade an existing installation

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#87]
We noticed that once you installed an older version of the project is not straightforward to go to the next one.

Since we now release on GitHub periodically this is a must.

Related to https://github.com/rapydo/issues/issues/18#issuecomment-318304833 comment in the rapydo framework, we may start with adding a 'teaser' of the command `rapydo upgrade` for the RC1, so that we have it for RC2.

**Comment by pdonorio** [comment]
The teaser was implemented. To be completed for the next milestone.

**Comment by chStaiger** [comment]
I created some documentation on how to get to v0.6.0 [here](https://github.com/EUDAT-B2STAGE/http-api/blob/0.5.2-docs/docs/testing/01-setup.md).

Tested for the development environment.

**Comment by pdonorio** [comment]
This has been completed. To be also tested from non developers. 

The upgrade works only with the rapydo controller >= `0.5.4`.

To update the controller if already installed:
```bash
$ VERSION="0.5.4"
$ (sudo) pip3 install --upgrade \
    git+https://github.com/rapydo/utils.git@$VERSION \
    requests==2.11.1 \
    git+https://github.com/rapydo/do.git@$VERSION \
```

Note to self: upgrading is a quite complex task to recover from if something fails (in the middle of the operation), at least automatically.
