### ISSUE TITLE
Integrate resources with PRC

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#93]
The official python iRODS driver doesn't handle resource directly.

We have to do something about this inside actions like put or retrieve (or list). E.g. see [here](https://github.com/rapydo/http-api/blob/0.5.4/restapi/flask_ext/flask_irods/client.py#L379).

**Comment by pdonorio** [comment]
@muccix do you think this is a priority or could we wait since we are dealing bigger problems?

**Comment by muccix** [comment]
I think we have other priorities for the moment

**Comment by pdonorio** [comment]
No time/effort for the first stable release.

This is not a big problem since right now just the main resource is used.
