### ISSUE TITLE
Current known bugs

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#96]
updated list of bugs to be fixed/checked

**Comment by pdonorio** [comment]
If the upload fails for auth reasons the cached object is not removed

**Comment by muccix** [comment]
Uploding a file with PUT and ?pid=true, without indicating the target file name in the URL fails with:

"errors": [
      "B2SAFE: Cannot extract metadata, object not found"
    ]

Resolved with this commit: 3135a76

**Comment by pdonorio** [comment]
`/auth/b2safeproxy` cannot login with a user who is mapped on multiple zones.

The error produced is:
```bash
irods.exception.MultipleResultsFound
```

**Comment by pdonorio** [comment]
> /auth/b2safeproxy cannot login with a user who is mapped on multiple zones.

Fixed with [this commit](https://github.com/rapydo/http-api/commit/bc07b17e78c585155308b4f529dbc431055e1ce5)

**Comment by pdonorio** [comment]
This issue will be dedicated to support bugs in production.
