### ISSUE TITLE
Using curl option -u to pass b2safe credentials

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#97]
At the moment the only way to get an access token using B2SAFE credentials is:

`curl https://b2stage.cineca.it/auth/b2safeproxy -d "username=<b2safe_username>&password=<b2safe_password>"`

The curl option "-u" does not seem to work.

Also 

`curl https://<b2safe_username>:<b2safe_password>@b2stage.cineca.it/auth/b2safeproxy`

should work, I think

**Comment by pdonorio** [comment]
It seems the `-u` option sends a new header `Authorization` with a digest, e.g.

```python
EnvironHeaders([('Host', 'localhost:8080'), ('Authorization', 'Basic cGlwcG86cGVwcGU='), ('User-Agent', 'curl/7.54.0'), ('Accept', '*/*')])
```

I may leverage [an existing flask snippet](http://flask.pocoo.org/snippets/8/) to recover this data.

**Comment by pdonorio** [comment]
Fixed
