### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#99]
Detailed description of the fields and possible values in the responses.
As we have done for the input field, do the same table for the response.

**Comment by muccix** [comment]
Replace pid with pid_await in PUT /api/registerd

**Comment by muccix** [comment]
Added the possibility to request a HEAD to verify whether the object already exists (to avoid to try to upload a big file already present)

**Comment by pdonorio** [comment]
Notes:

1. we should create a content index, see the [b2handle](http://eudat-b2safe.github.io/B2HANDLE/) as example
2. With this issue let's try to fix [all docs issues](https://github.com/EUDAT-B2STAGE/http-api/issues?q=is%3Aissue+is%3Aopen+label%3Adocs)

**Comment by pdonorio** [comment]
Also [a way to test responses when uploading with streaming](https://github.com/EUDAT-B2STAGE/http-api/issues/20#issuecomment-334760093) should be clarified somewhere.

**Comment by pdonorio** [comment]
Re-test and document [the new `/api/publish` endpoint](https://github.com/EUDAT-B2STAGE/http-api/issues/72#issuecomment-336857556) in usage.

**Comment by pdonorio** [comment]
See #41, there could be "*iRODS instance setup in a way so it should NOT be able to put data*". So we must say in the docs that this is not allowed with the current HTTP API release.

**Comment by pdonorio** [comment]
Specify that with streaming upload of a file to a collection path the trailing slash is mandatory due to Flask internals. This does not occurs with normal (form) upload.

**Comment by pdonorio** [comment]
There's some [testing](https://github.com/EUDAT-B2STAGE/http-api/tree/82c101b57185a54f49cd4db903d60e32023c2672/docs/testing) to check and real feedback on the [quickstart](https://github.com/merretbuurman/http-api/blob/3ad8329d1fd5471f4f2167e4fa1e38e907c69afc/docs/quick_start.md)

**Comment by pdonorio** [comment]
> Replace `pid` with `pid_await` in PUT `/api/registered`

Done with 1f24a2c67b9d4be61cb4ac52ea283cd26d5000f0

**Comment by pdonorio** [comment]
Clarify also that `b2safe` and `b2access` authentication [are mutually exclusive](https://github.com/EUDAT-B2STAGE/http-api/issues/79#issuecomment-319417935)

**Comment by pdonorio** [comment]
See the [new index](https://github.com/EUDAT-B2STAGE/http-api/blob/1.0.0/README.md#documentation)

**Comment by pdonorio** [comment]
Add instructions to create the account for the HTTP API in B2ACCESS to the docs

---

1. Go to https://b2access.eudat.eu/home/
2. Click on the register a new account link
3. Oauth 2.0 Client Registration Form
4. As “OAuth client return URL” indicate https://YOUR_SERVER/auth/authorize

When you receive your credentials you should apply them in the `project_configuration.yaml`

**Comment by pdonorio** [comment]
Add:

- [ ] CentOS instructions (from interaction with Beatrix)
- [ ] Production example file (from interaction with Eko)
- [ ]  Clarify also that b2safe and b2access authentication are mutually exclusive
- [ ] Remove delete in registered domain and clarify why

**Comment by pdonorio** [comment]
Ready to release 1.0.2
